---
- name: Playbook para configurar HTTPS
  hosts: backend_ip
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:
    - name: Quitamos la base de datos
      mysql_db:
        name: "{{ wordpress.db.name }}"
        state: absent
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Creamos la base de datos
      mysql_db:
        name: "{{ wordpress.db.name }}"
        state: present
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Quitamos el usuario si esiste
      mysql_user:
        name: "{{ wordpress.db.user }}"
        host: "{{ FRONTEND_NETWORK }}"
        state: absent
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Creamos el usuario
      mysql_user:
        name: "{{ wordpress.db.user }}"
        password: "{{ wordpress.db.password }}"
        host: "{{ FRONTEND_NETWORK }}"
        priv: "{{ wordpress.db.name }}.*:ALL"
        state: present
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
