- name: Configurar NFS Servidor
  hosts: nfs_server
  become: yes
  
  vars_files:
    - ../vars/variables.yaml

  tasks:
    - name: Instalar NFS Server
      apt:
        name: nfs-kernel-server
        state: present

    - name: Crear directorio compartido
      file:
        path: "{{ directories.wordpress }}"
        state: directory
        owner: nobody
        group: nogroup
        mode: '0755'

    - name: Copiar configuración de NFS
      copy:
        src: ../nfs/exports
        dest: /etc/exports   

    - name: Reemplazar valores en /etc/exports
      replace:
        path: /etc/exports
        regexp: 'FRONTEND_NETWORK'
        replace: '{{ network.frontend }}'

    - name: Reiniciar NFS Server
      systemd:
        name: nfs-kernel-server
        state: restarted
