---
- name: Configurar NFS Cliente
  hosts: frontend1,frontend2
  become: yes
  vars_files:
    - /home/ubuntu/practica-3.2/vars/variables.yaml
  tasks:
    - name: Actualizar sistema
      apt:
        update_cache: yes
    
    - name: Instalar cliente NFS
      apt:
        name: nfs-common
        state: present

    - name: Montar directorio NFS
      mount:
        path: "{{ directories.wordpress }}"
        src: "{{ ip.nfs_server }}:{{ directories.wordpress }}"
        fstype: nfs
        opts: auto,nofail,noatime,nolock,intr,tcp,actimeo=1800
        state: mounted